### ISSUE TITLE
Add "min" option so that sliding can control the brightness but does not turn the light off

### ISSUE THREAD

**Issue by nadlabak** [nicufarmache/lovelace-big-slider-card#15]
I want to be able to slide all the way left to set the light to its minimal brightness but keep the light on. To turn the light off, I prefer to use hold or tap but not sliding.

E.g. slider-entity-row by Thomas Lovén has "min" and "max" options that can be used for that purpose.
Thank you!

**Comment by nicufarmache** [comment]
Good ideea
