### ISSUE TITLE
Scrolling not possible

### ISSUE THREAD

**Issue by lasse9000** [nicufarmache/lovelace-big-slider-card#16]
Great work. Look a lot nicer when they other options out there. But if i have a lot of Them, i can't scoll on my mobil without changeing the light. Maybe it's possible to only change the light then scolling sideways. Hope it make sensor.

**Comment by nicufarmache** [comment]
Hey. Yes, I know about this problem but I haven't thought about a solution yet. I'll try to fix it somehow

**Comment by nicufarmache** [comment]
I think I fixed it in version 1.0.10. Try to see if it's working ok for you now.

In case it's still accidentally changing the light. Try to set the `min_slide_time` to something like `200`
This wil ignore interactions that are shorter than that time
