### ISSUE TITLE
Slider is square when transitioning between states even with a rounded them on mobile app.

### ISSUE THREAD

**Issue by ironcrafter54** [nicufarmache/lovelace-big-slider-card#21]
Color transition animation does not work properly on the home assistant mobile app, Same issue in my previous report except the fix for safari the web browser did not fix the mobile app.

**Comment by nicufarmache** [comment]
Can you please try again with the latest version (1.1.1) and check if it's still happening?

**Comment by ironcrafter54** [comment]
Unfortunately it still happens on the latest version, but I believe it is an issue with the home assistant app, not your card since it also happens on other cards. Ill make a bug report for the app, I think you can close this bug.

**Comment by nicufarmache** [comment]
I managed to test on an iPhone with the app now and for some reason it looks ok to me.
Home Assistant Companion 2023.2 (2023.444)
IOS 16.3.1

https://user-images.githubusercontent.com/5407920/230619093-174ee0fe-89e4-4aaf-b95e-177c5f51c752.mp4

**Comment by ironcrafter54** [comment]
I updated the app and the issue is fixed 😄, thanks for having a look at my issues. Your slider cards are now looking very nice on my dashboard with no issue whatsoever.
Have a good weekend.

**Comment by nicufarmache** [comment]
Thank you for the update :smile: 
Have a nice weekend too!
