### ISSUE TITLE
Wrong brightness percentage

### ISSUE THREAD

**Issue by Kleeraphie** [nicufarmache/lovelace-big-slider-card#23]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2023.3.6

**Last working release (if known):**

**Browser and Operating System:**
Google Chrome 112.0.5615.49, Windows 11

**Description of problem:**

When changing the brightness of a WLED light, the card sometimes shows a higher brightness percentage than the Home Assistant more-info card.
<img src="https://lh3.googleusercontent.com/pw/AMWts8AQwZD13hSjGZZBUksVIMWEul95Tthb3bVGqCcSopomelwfYc69rj9H77sD5TwtwQ4PADP71VxBpXllOAnraErfyCR8r_NxkOyouWFLXnwfP0TkWw_PFTMlr9MOW0WibZsiZjpZaHy8gj4L5IqjaIwu8Q=w1371-h910-s-no?authuser=0">

In this example, WLED reports a brightness level of 97 out of 255, which is 97/255 = 38.04%. It seems like this card rounds the brightness up to 39%, while Home Assistant only rounds up if the brightness level is >= *.5%, so it rounds down to 38%.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by nicufarmache** [comment]
I just merge a pull request that changed the behaviour so that it rounds at .5 
Try the next version which will be out soon and see if this fixed your issue

**Comment by Kleeraphie** [comment]
This fixed the issue. Thank you.
