### ISSUE TITLE
Show "Unavailable" for offline devices

### ISSUE THREAD

**Issue by xertux** [nicufarmache/lovelace-big-slider-card#26]
Hello,

i can't differentiate if my light is really "off" or "offline" because the slider shows "off" on both occasions.

I would like to see "Unavailable" or another  indication that the device is out of reach or offline and therefor i wouldn't react with the slider (toggle, hold or slide)

Thank you.

**Comment by nicufarmache** [comment]
In the next version it ill look a bit dimmer when the entity is unavailable and also you will not be able to slide it
