### ISSUE TITLE
Feature Request : Square button shape

### ISSUE THREAD

**Issue by kalhimeo** [nicufarmache/lovelace-big-slider-card#28]
**Is your feature request related to a problem? Please describe.**
In order to integrate the card better with other button cards, it would be nice to have an option to make it a 'square' shape

**Describe the solution you'd like**
Just have an optional "button" setting to render the card as a square

**Describe alternatives you've considered**
n/a

**Additional context**
Thank you so much already for this card, it is really nice !

**Comment by nicufarmache** [comment]
By 'sqare' you mean to not have rounded corners?

**Comment by kalhimeo** [comment]
that s great, thank you very much !
