### ISSUE TITLE
Card not working on nest hub

### ISSUE THREAD

**Issue by BuergerJulian** [nicufarmache/lovelace-big-slider-card#29]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Browser and Operating System:**
Google Cast, Nest Hub

**Description of problem:**
Card not available on Google Nest Hub "Custom element doesn't exist: big-slider-card."

**Javascript errors shown in the web inspector (if applicable):**
No access to web inspector.

**Comment by nicufarmache** [comment]
I tried but I can't really test on the nest hub since I don't have one :(
