### ISSUE TITLE
Problem with Bar Height - Please Add Bar Height

### ISSUE THREAD

**Issue by FancyNerd92** [nicufarmache/lovelace-big-slider-card#35]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
I want you add bar height because if i change the height of bar with CSS (card-mod etc.) I have this problem: https://i.imgur.com/Vbmu6Ay.gif on every refresh on every tab that i have the bar. It loads first the original height and after that the CSS fixed height. So it's like have bug/lag...

**Additional context**
I see your latest update that you add border_width and I was happy about.. but after some time it was clear to me what's the purpose of this... Please add a general height and it will be perfect!

**Comment by nicufarmache** [comment]
fixed in version 1.1.3-beta

I added a new `height` option

**Comment by FancyNerd92** [comment]
It works like a charm!! It fix the problem! Thanks a lot!!!!
