### ISSUE TITLE
Add % Value option

### ISSUE THREAD

**Issue by nicufarmache** [nicufarmache/lovelace-big-slider-card#4]
### Discussed in https://github.com/nicufarmache/lovelace-big-slider-card/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **markus99** February 28, 2023</sup>
Any thought to add a % value (either after name or as 2nd line below?)

Mushroom sliders aren't great, but what I'm using now and can show the value like this:

![image](https://user-images.githubusercontent.com/2835274/221998338-4f92fc01-b0bc-447f-9a6a-6268d285aaae.png)
</div>

**Comment by antonio1475** [comment]
I fully agree. It was the first thing I missed when testing this card (which btw is great and has a great potential - this type of slider was requested a lot in Mushroom)

I would also consider making the name bold, and the brightness in gray below (also bold) - based on Mushroom styling, which imho is great.


![image](https://user-images.githubusercontent.com/63130724/222701406-b9ed9a36-6a50-4cad-96d3-aa3421e41655.png)

![image](https://user-images.githubusercontent.com/63130724/222701849-712bb7da-1c84-48a8-b2fb-d7987cf47dd8.png)

**Comment by nicufarmache** [comment]
published in release [1.0.8](https://github.com/nicufarmache/lovelace-big-slider-card/releases/tag/1.0.8)
